proc float Addition(float $input[]){
    float $total = 0;
    for($i = 0; $i < size($input); $i++)
    {
        $total += $input[$i];
    }
    return $total;
}
//float $Aresult = Addition({1, 3, 17});
//print("The total sum is: " + $Aresult + "\n");

proc float Subtraction(float $input[])
{
    float $total = $input[0];
    for($i = 1; $i < size($input); $i++)
    {
        $total -= $input[$i];
    }
    return $total;
}
//float $Sresult = Subtraction({20, 5, 3, 2, 3});
//print("The total sum is: " + $Sresult + "\n");

proc float Multiplication(float $input[])
{
    float $total = $input[0];
    for($i = 1; $i < size($input); $i++)
    {
        $total *= $input[$i];
    }
    return $total;
}
//float $Mresult = Multiplication({2, 3})
//print("The total sum is:" + $Mresult + "\n")

proc float Division(float $input[])
{
    float $total = $input[0];
    for($i = 1; $i < size($input); $i++)
    {
        $total /= $input[$i];
    }
    return $total;
}
//float $Dresult = Division({20, 5, 2});
//print("The total sum is: " + $Dresult + "\n");

proc float Power(float $base, float $exponent) 
{
    return `pow $base $exponent`;
}

//float $Presult = Power(3, 5);
//print("The result is: " + $Presult + "\n");

proc float Mean(float $input[])
{
    float $total = 0;
    for($i = 0; $i < size($input); $i++)
    {
        $total += $input[$i];
    }
    $total /= size($input);
    return $total;
}

//float $mean_result = Mean({3, 6, 1, 9, 5});
//print("The result is: " + $mean_result + "\n");

proc float Median(float $input[]) 
{
    float $sorted[] = `sort $input`;
    float $total = 0;
    if (size($sorted) % 2 == 0) {
        int $even_number_one = size($sorted) / 2;
        int $even_number_two = $even_number_one - 1;
        $total = ($sorted[$even_number_one] + $sorted[$even_number_two]) / 2.0;
    } else {
        int $odd_number = size($sorted) / 2;
        $total = $sorted[$odd_number];
    }
    return $total;
}

//float $Median_result = Median({7, 2, 9, 4, 5});
//print("The result is: " + $Median_result + "\n");